from pathlib import Path

from paicorelib.framelib import FrameArrayType
from pynq import Overlay  # pyright: ignore

from .hw_hierarchy import HwDatapathHier

class ZynqPlatformOverlay(Overlay):
    pl_datapath: HwDatapathHier

    def __init__(
        self, bitfile: Path | str, start_debug_bridge: bool = False, **kwargs
    ) -> None: ...
    def reset_regfile(self) -> None: ...
    def write_reg(self, addr: int, value: int) -> None: ...
    def read_reg(self, addr: int, length: int = 4) -> int: ...
    def send_frame(self, frame: FrameArrayType) -> int: ...
    def recv_frame(self, size: int) -> FrameArrayType: ...
    def reset_chip(self, *chip_idx: int) -> None: ...
    def set_uart_debug(self, uart_idx: int, debug: bool = True) -> None: ...
    def send_uart_cmd(self, uart_idx: int, uart_cmd_bytes: bytes) -> bytes: ...
