from pathlib import Path
from pynq import Overlay
from paiboard.types import FrameArrayType

from .hw_hierarchy import HwDatapathHier

class Overlay:
    def __init__(
        self,
        bitfile_name: str,
        dtbo=None,
        download=True,
        ignore_version=False,
        device=None,
        gen_cache=False,
    ): ...
    def is_loaded(self) -> bool: ...
    def reset(self) -> None: ...
    def load_ip_data(self, ip_name: str, data: str) -> None: ...

class ZynqPlatformOverlay(Overlay):
    pl_datapath: HwDatapathHier

    def __init__(
        self, bitfile: Path | str, start_debug_bridge: bool = False, **kwargs
    ) -> None: ...
    def reset_regfile(self) -> None: ...
    def write_reg(self, addr: int, value: int) -> None: ...
    def read_reg(self, addr: int, length: int = 4) -> int: ...
    def send_frame(self, frame: FrameArrayType) -> int: ...
    def recv_frame(self, size: int) -> FrameArrayType: ...
    def reset_chip(self, *chip_idx: int) -> None: ...
    def set_uart_debug(self, uart_idx: int, debug: bool = True) -> None: ...
    def send_uart_cmd(self, uart_idx: int, uart_cmd_bytes: bytes) -> bytes: ...
