from typing import ClassVar
from pynq import DefaultHierarchy

from paiboard.types import FrameArrayType

class DefaultHierarchy:
    def __init__(self, description) -> None: ...
    @staticmethod
    def checkhierarchy(description) -> bool: ...
    def download(self, bitfile_name: str, dtbo=None, program=True) -> None: ...

class HwDatapathHier(DefaultHierarchy):
    UART_IP_NAMES: ClassVar[list[str]]
    DMA_IP_NAME: ClassVar[str]
    GPIO_IP_NAME_CHIP_RST: ClassVar[str]
    DEBUG_BRIDGE_IP_NAME: ClassVar[str]

    REGFILE_BASE_ADDR: ClassVar[int]
    REGFILE_ADDR_RANGE: ClassVar[int]

    def __init__(self, description) -> None: ...
    def write_axi_gpio_chip_reset(self, value: int) -> None: ...
    def write_regfile(self, addr: int, value: int) -> None: ...
    def read_regfile(self, addr: int, length: int = 4) -> int: ...
    def write_dma(self, data: FrameArrayType) -> int: ...
    def read_dma(self, size: int) -> FrameArrayType: ...
    def axi_uart_debug(self, uart_idx: int, enable: bool = True) -> None: ...
    def send_uart_cmd(self, uart_idx: int, cmd: bytes) -> bytes: ...
    def start_debug_bridge(self, port: int = 2542) -> None: ...
    def stop_debug_bridge(self) -> None: ...
    @staticmethod
    def checkhierarchy(description) -> bool: ...
